region = "us-east-1"
instance_type = "t2.micro"
instance_name = "terraform-instance"
instance_az = "us-east-1a"
tfstate_bucket_name = "eksterrabuckethectoruseast1"
tfstate_bucket_key = "backend/backend.tfstate"
dynamodb_table_name = "dynamo-db-tf-state"